mainprogram: main/main.cpp zoo/zoo.cpp cage/cage.cpp point/point.cpp animal/animal.cpp driver/driver.cpp 
	g++ main/main.cpp zoo/zoo.cpp cage/cage.cpp point/point.cpp animal/animal.cpp driver/driver.cpp -std=c++11 -o mainprogram
clean:
	rm -f *.o *~ mainprogram
exec:
	./mainprogram
